/**
 * LM_TEXT —— 灵脉（修炼）模块术语表   [设定映射：gooboo · mining → 修仙]
 * ============================================================
 * 职责：只提供显示文案，不含任何逻辑与数值。
 *   - LM_ENTRY 通过 LM_TEXT 取「模块名 / 秘法名 / 灵资名 / 道录名 / 悟道名」；
 *   - 未命中的键自动回落原键名，缺项不会报错；
 *   - 键规则（与 lm_entry.js 取值口径严格对齐）：
 *       UPGRADE   键 = gooboo 升级原键（去掉 lm_ 前缀），如 damageUp
 *       CURRENCY  键 = 运行时货币键（含 lm_ 前缀），如 lm_scrap
 *       STAT      键 = 运行时统计键去掉 lm_ 前缀，如 maxDepth0
 *       UNLOCK    键 = gooboo 解锁完整 id，如 lmPickaxeCrafting
 *   - 数值与公式全部来自 lm_data.js / lm_store.js，本文件不参与数值设计。
 */
const LM_TEXT = {
  /* ---------------- 模块本体 ---------------- */
  MODULE: {
    name: '灵脉',
    label: '修炼 · 灵脉',
    desc: '凿层岩、引灵气入脉；以灵气参悟秘法、铸造法器，逐层深入灵脉，直至渡劫飞升。'
  },

  /* ---------------- 通用词条（面板提示用） ---------------- */
  TERMS: {
    depth: '道行',
    depthLayer: '层',
    scrap: '灵气',
    damage: '破岩',
    toughness: '韧性',
    oreGain: '灵矿产出',
    oreCap: '灵矿容量',
    oreQuality: '灵矿品质',
    rareEarthGain: '灵材产出',
    gasGain: '灵气产出（气）',
    premiumOreCap: '高阶矿容量',
    pickaxeCraftingSlots: '铸位',
    pickaxePremiumCraftingSlots: '高阶铸位',
    pickaxeCraftingPower: '铸力',
    pickaxeCraftingQuality: '铸质',
    pickaxe: '灵锄',
    pickaxePower: '灵锄锋锐',
    durability: '层岩余量',
    dweller: '驻脉',
    depthDwellerSpeed: '驻脉速度',
    depthDwellerMax: '驻脉上限',
    resinMax: '灵脂上限',
    smelteryTime: '炼化时间',
    smelteryTemperature: '炼化温度',
    enhancementMax: '附灵上限',
    prestigeIncome: '飞升收益',
    ore: '灵矿',
    bar: '灵锭',
    rareEarth: '灵材',
    gas: '灵气（气）',
    prestige: '飞升',
    craft: '铸器',
    upgrade: '秘法',
    unlock: '悟道',
    smeltery: '炼化炉',
    enhancement: '附灵',
    beacon: '灵标',
    crystal: '玉晶',
    automation: '自动修行',
    note18: '炼化炉需先悟得「炼化之道」方可启用。',
    note25: '附灵台需先悟得「附灵之道」方可启用。',
    note30: '聚灵瓮可暂存灵气，超量部分按衰减留存。'
  },

  /* ---------------- 灵资 / 货币（键含 lm_ 前缀） ---------------- */
  CURRENCY: {
    lm_scrap: '灵气',

    lm_oreAluminium: '皓铝矿',
    lm_oreCopper: '赤铜矿',
    lm_oreTin: '苍锡矿',
    lm_oreIron: '玄铁矿',
    lm_oreTitanium: '天钛矿',
    lm_orePlatinum: '白铂矿',
    lm_oreIridium: '幽铱矿',
    lm_oreOsmium: '寒锇矿',
    lm_oreLead: '重铅矿',

    lm_barAluminium: '皓铝锭',
    lm_barBronze: '青铜锭',
    lm_barSteel: '玄钢锭',
    lm_barTitanium: '天钛锭',
    lm_barShiny: '流光锭',
    lm_barIridium: '幽铱锭',
    lm_barDarkIron: '暗铁锭',

    lm_granite: '岩髓',
    lm_salt: '灵盐',
    lm_coal: '炭精',
    lm_sulfur: '硫髓',
    lm_niter: '硝晶',
    lm_obsidian: '曜石',
    lm_deeprock: '渊岩',
    lm_glowshard: '萤辉石',
    lm_limestone: '石乳',
    lm_moonshard: '月华碎',
    lm_phosphorus: '磷火',

    lm_smoke: '灵烟',
    lm_ember: '烬火',
    lm_resin: '灵脂',
    lm_crystalGreen: '青玉晶',
    lm_crystalYellow: '金玉晶',

    lm_helium: '青冥气',
    lm_neon: '赤霞气',
    lm_argon: '紫霄气',
    lm_krypton: '玄阴气',
    lm_xenon: '湛精气',
    lm_radon: '碧落气',

    lm_goldenHammer: '鎏金锤',
    gem_ruby: '赤玉'
  },

  /* ---------------- 道录统计（键去 lm_ 前缀） ---------------- */
  STAT: {
    maxDepth0: '道行纪录',
    maxDepth1: '幽行道行',
    depthDweller0: '驻脉修行',
    depthDwellerCap0: '驻脉上限',
    depthDweller1: '幽行驻脉',
    depthDwellerCap1: '幽行驻脉上限',
    totalDamage: '累计破岩',
    maxDamage: '最高一击',
    craftingCount: '铸器次数',
    craftingLuck: '铸器运数',
    craftingWasted: '耗损灵气',
    dwellerCapHit: '驻脉满溢',
    enhancementHighest: '附灵最高阶',
    timeSpent: '修行时长',
    relicActivesUsed: '法器动用',
    bestPrestige0: '最佳飞升',
    bestPrestige1: '幽行最佳飞升',
    prestigeCount: '飞升次数',
    maxDepthSpeedrun: '疾行道行'
  },

  /* ---------------- 悟道法门（unlock id） ---------------- */
  UNLOCK: {
    lmPickaxeCrafting: '法器铸造',
    lmDepthDweller: '驻脉修行',
    lmSmeltery: '炼化之道',
    lmEnhancement: '附灵之道',
    lmResin: '灵脂凝取',
    lmGasSubfeature: '御气分支',
    lmSmoke: '灵烟感应',
    lmAdvancedCardPack: '进阶道牌',
    lmLuxuryCardPack: '奢华道牌',

    lmScrap: '灵气初显',
    lmOreAluminium: '皓铝现世',
    lmOreCopper: '赤铜现世',
    lmOreTin: '苍锡现世',
    lmOreIron: '玄铁现世',
    lmOreTitanium: '天钛现世',
    lmOrePlatinum: '白铂现世',
    lmOreIridium: '幽铱现世',
    lmOreOsmium: '寒锇现世',
    lmOreLead: '重铅现世',
    lmBarAluminium: '皓铝成锭',
    lmBarBronze: '青铜成锭',
    lmBarSteel: '玄钢成锭',
    lmBarTitanium: '天钛成锭',
    lmBarShiny: '流光成锭',
    lmBarIridium: '幽铱成锭',
    lmBarDarkIron: '暗铁成锭',
    lmGranite: '岩髓可采',
    lmSalt: '灵盐可采',
    lmCoal: '炭精可采',
    lmSulfur: '硫髓可采',
    lmNiter: '硝晶可采',
    lmObsidian: '曜石可采',
    lmDeeprock: '渊岩可采',
    lmGlowshard: '萤辉石可采',
    lmLimestone: '石乳可采',
    lmMoonshard: '月华碎可采',
    lmPhosphorus: '磷火可采',
    lmSmoke: '灵烟可引',
    lmEmber: '烬火可引',
    lmResin: '灵脂可凝',
    lmHelium: '青冥气可采',
    lmNeon: '赤霞气可采',
    lmArgon: '紫霄气可采',
    lmKrypton: '玄阴气可采',
    lmXenon: '湛精气可采',
    lmRadon: '碧落气可采',
    lmCrystalGreen: '青玉晶可获',
    lmCrystalYellow: '金玉晶可获',

    lmCompressAluminium: '皓铝压缩',
    lmCompressCopper: '赤铜压缩',
    lmCompressTin: '苍锡压缩',
    lmCompressIron: '玄铁压缩',
    lmCompressTitanium: '天钛压缩',
    lmCompressPlatinum: '白铂压缩',
    lmCompressIridium: '幽铱压缩',
    lmCompressOsmium: '寒锇压缩',
    lmCompressLead: '重铅压缩',

    lmBeaconHope: '灵标·祈愿',
    lmBeaconPiercing: '灵标·穿透',
    lmBeaconRich: '灵标·丰饶',
    lmBeaconWonder: '灵标·奇观'
  },

  /* ---------------- 秘法升级（键为 gooboo 原键，已去 lm_ 前缀） ---------------- */
  UPGRADE: {
    /* --- 常规秘法（upgrade） --- */
    damageUp: '破岩淬力',
    scrapGainUp: '灵气汲取',
    scrapCapacityUp: '灵气纳蓄',
    aluminiumCache: '皓铝储量',
    aluminiumHardening: '皓铝淬炼',
    craftingStation: '铸器台',
    forge: '熔炉',
    oreSlots: '灵矿格位',
    compressor: '灵压囊',
    copperCache: '赤铜储量',
    aluminiumTanks: '皓铝灵罐',
    aluminiumAnvil: '皓铝灵砧',
    hullbreaker: '裂岳锤',
    copperTanks: '赤铜灵罐',
    depthDweller: '驻脉真人',
    aluminiumExpansion: '皓铝扩容',
    refinery: '精炼炉',
    copperExpansion: '赤铜扩容',
    drillFuel: '钻灵油',
    graniteHardening: '岩髓淬炼',
    smeltery: '炼化炉',
    oreShelf: '灵矿架',
    heatShield: '避火罩',
    tinCache: '苍锡储量',
    furnace: '煅炉',
    bronzeCache: '青铜储量',
    ironCache: '玄铁储量',
    oreWashing: '洗灵矿',
    ironExpansion: '玄铁扩容',
    bronzeDrill: '青铜灵钻',
    ironHardening: '玄铁淬炼',
    ironFilter: '玄铁滤网',
    masterForge: '宗师炉',
    starForge: '星辉炉',
    magnet: '引灵磁石',
    bronzeFilter: '青铜滤网',
    enhancingStation: '附灵台',
    enhancingHammer: '附灵锤',
    warehouse: '灵库',
    corrosiveFumes: '蚀骨烟',
    smeltingSalt: '熔灵盐',
    titaniumExpansion: '天钛扩容',
    emberForge: '烬火炉',
    bronzeForge: '青铜炉',
    titaniumCache: '天钛储量',
    smallBombs: '小爆符',
    giantForge: '巨灵炉',
    gunpowder: '雷火粉',
    nitricAcid: '硝灵酸',
    metalDetector: '探灵盘',
    nails: '玄钉',
    recycling: '回炉术',
    stickyJar: '聚灵瓮',
    acidVial: '蚀灵瓶',
    scanning: '神识扫描',
    largerSurface: '阔面台',
    qualityWorkbench: '精工台',
    titaniumForge: '天钛炉',
    dynamite: '爆灵符',
    platinumExpansion: '白铂扩容',
    hiddenStash: '秘藏格',
    platinumCache: '白铂储量',
    colossalOreStorage: '巨灵矿仓',
    smallOreStorage: '小灵矿仓',
    titaniumBombs: '天钛雷',
    titaniumPickaxe: '天钛灵锄',
    undergroundRadar: '地脉罗盘',
    scrapShelf: '灵气架',
    iridiumExpansion: '幽铱扩容',
    iridiumCache: '幽铱储量',
    stonecutter: '剖石刀',
    iridiumTreetap: '幽铱导灵管',
    deepCuts: '深凿',
    iridiumBombs: '幽铱雷',
    oreBag: '灵矿袋',
    osmiumExpansion: '寒锇扩容',
    osmiumCache: '寒锇储量',
    darkBombs: '玄幽雷',
    colossalScrapStorage: '巨灵气仓',
    stoneDissolver: '化石散',
    leadExpansion: '重铅扩容',

    /* --- 深脉秘法（upgrade2） --- */
    fumes: '灵烟蕴',
    smallCrate: '小灵箱',
    giantCrate: '巨灵箱',
    morePressure: '灵压增',
    gasDweller: '御气修行',
    piston: '灵压活塞',
    pollution: '浊气',
    particleFilter: '净灵滤网',
    hotAirBalloon: '云舟',
    conductor: '导灵铜',
    vent: '泄灵口',
    urn: '承灵瓮',
    lunarBlessing: '太阴庇佑',
    harvester: '采灵机',
    chalkboard: '演算石板',
    graphiteRod: '墨晶棒',
    minecart: '灵矿辇',
    moonstone: '月华石',
    nightVisionDevice: '夜视灵镜',
    enrichedCrystal: '凝晶术',
    matches: '引火符',
    smokeStabilizer: '定烟珠',
    elevator: '升灵梯',
    shovel: '灵铲',
    smoker: '聚烟炉',

    /* --- 晶枢秘传（upgradePremium） --- */
    moreDamage: '破岩更利',
    moreScrap: '灵气更丰',
    moreGreenCrystal: '青玉晶更丰',
    moreRareEarth: '灵材更丰',
    fasterSmeltery: '炼化更快',
    moreResin: '灵脂更丰',
    premiumCraftingSlots: '铸位更多',
    moreAluminium: '皓铝更丰',
    moreCopper: '赤铜更丰',
    moreTin: '苍锡更丰',
    moreIron: '玄铁更丰',
    moreTitanium: '天钛更丰',
    morePlatinum: '白铂更丰',
    moreIridium: '幽铱更丰',
    moreOsmium: '寒锇更丰',
    moreLead: '重铅更丰',
    moreHelium: '青冥气更丰',
    moreSmoke: '灵烟更丰',
    moreNeon: '赤霞气更丰',
    moreArgon: '紫霄气更丰',
    moreKrypton: '玄阴气更丰',

    /* --- 飞升秘传（upgradePrestige） --- */
    crystalBasics: '晶枢·根基',
    crystalTips: '晶枢·锋芒',
    crystalStorage: '晶枢·纳蓄',
    crystalLens: '晶枢·灵镜',
    crystalAluminiumStorage: '晶枢·皓铝仓',
    crystalCopperStorage: '晶枢·赤铜仓',
    crystalTinStorage: '晶枢·苍锡仓',
    crystalIronStorage: '晶枢·玄铁仓',
    crystalTitaniumStorage: '晶枢·天钛仓',
    crystalPlatinumStorage: '晶枢·白铂仓',
    crystalIridiumStorage: '晶枢·幽铱仓',
    crystalOsmiumStorage: '晶枢·寒锇仓',
    crystalLeadStorage: '晶枢·重铅仓',
    crystalDrill: '晶枢·灵钻',
    crystalDetector: '晶枢·探灵',
    crystalReplicator: '晶枢·化灵',
    crystalPreservarium: '晶枢·养灵',
    crystalTools: '晶枢·器用',
    crystalExplosives: '晶枢·爆灵',
    crystalRefinery: '晶枢·精炼',
    crystalSmeltery: '晶枢·炼化',
    crystalEnhancer: '晶枢·附灵',
    crystalTreetap: '晶枢·导灵',
    crystalSalt: '晶枢·灵盐',
    crystalBottle: '晶枢·灵瓶',
    crystalSafe: '晶枢·秘藏',
    crystalEngine: '晶枢·灵机',
    crystalCoal: '晶枢·炭精',
    crystalTruck: '晶枢·灵车',
    crystalExpansion: '晶枢·扩容',
    crystalTnt: '晶枢·雷火',
    crystalBeacon: '晶枢·灵标',
    crystalNiter: '晶枢·硝晶',
    crystalBunker: '晶枢·灵堡',
    crystalOreBag: '晶枢·灵矿袋',
    crystalSpikes: '晶枢·锐刺',
    crystalBooster: '晶枢·助灵',
    heliumReserves: '青冥气蕴',
    crystalSmoke: '晶枢·灵烟',
    crystalConductor: '晶枢·导灵铜',
    crystalFusion: '晶枢·灵合',
    neonReserves: '赤霞气蕴',
    crystalRefuge: '晶枢·静室',
    crystalCave: '晶枢·灵窟',
    crystalFilter: '晶枢·滤网',
    heliumWarehouse: '青冥气库',
    crystalTunnel: '晶枢·灵脉',
    argonReserves: '紫霄气蕴',
    crystalDust: '晶枢·灵尘',
    neonWarehouse: '赤霞气库',
    crystalBombs: '晶枢·爆雷',
    crystalCollector: '晶枢·聚灵',
    kryptonReserves: '玄阴气蕴',
    crystalResort: '晶枢·静苑'
  },

  /* ---------------- 灵矿 / 炼化 / 附灵（术语备用，UI 扩展时取用） ---------------- */
  ORE: {
    oreAluminium: '皓铝矿',
    oreCopper: '赤铜矿',
    oreTin: '苍锡矿',
    oreIron: '玄铁矿',
    oreTitanium: '天钛矿',
    orePlatinum: '白铂矿',
    oreIridium: '幽铱矿',
    oreOsmium: '寒锇矿',
    oreLead: '重铅矿'
  },

  SMELTERY: {
    aluminium: '皓铝锭',
    bronze: '青铜锭',
    steel: '玄钢锭',
    titanium: '天钛锭',
    shiny: '流光锭',
    iridium: '幽铱锭',
    darkIron: '暗铁锭'
  },

  ENHANCEMENT: {
    barAluminium: '皓铝附灵',
    barBronze: '青铜附灵',
    barSteel: '玄钢附灵',
    barTitanium: '天钛附灵',
    barShiny: '流光附灵',
    barIridium: '幽铱附灵',
    barDarkIron: '暗铁附灵'
  }
};
