/**
 * HO_TEXT —— 降妖（horde）模块术语表   [设定映射：gooboo · horde → 修仙降妖]
 * ============================================================
 * 职责：只提供显示文案，不含任何逻辑与数值。
 * 键口径：CURRENCY 键 = 运行时货币键（含 horde_ 前缀）
 *        ITEM     键 = gooboo 装备/物品原键（去 horde_ 前缀）
 *        CLASS    键 = gooboo 战斗职业原键
 *        SKILL    键 = 技能基名（视图会剥掉 _N 递增后缀后查表）
 *        AREA     键 = gooboo 区域原键
 *        ENEMY/TOWER/ELEMENT/TRINKET/RELIC/TAG/SIGIL 键 = gooboo 原键
 *        UPGRADE/UPGRADE2/PREMIUM/PRESTIGE = 各类升级原键
 * 未命中回落原键名，缺项不会报错。
 */
const HO_TEXT = {
  /* ---------------- 模块本体 ---------------- */
  MODULE: {
    name: '降妖',
    label: '降妖 · 战场',
    desc: '临黑暗妖境，屠妖破阵。积妖骨妖魄，砺招开魄、携宝传承，从一介散修斩至轮回者。'
  },

  /* ---------------- 通用词条 ---------------- */
  TERMS: {
    horde: '降妖',
    player: '主角',
    zone: '妖界',
    boss: '妖王',
    combo: '连斩',
    comboRequired: '连斩需求',
    enemy: '妖物',
    equipment: '灵械',
    heirloom: '传承',
    souls: '轮回',
    battlePass: '战令',
    prestige: '轮回',
    upgrades: '道法',
    taunt: '燃烧精血',
    raid: '讨伐',
    tower: '镇妖塔',
    crown: '王冕',
    zoneBoss: '妖王·',
    zoneEndless: '无尽',
    resurrect: '重生',
    autocast: '自动',
    chance: '契机',
    cleared: '已破',
    fighting: '鏖战',
    fleeBoss: '激斗妖王',
    defeatBoss: '击破妖王',
    fightBoss: '对阵妖王',
    reachBoss: '在此妖界击破连斩以唤妖王',
    monsterPartHint: '妖物自第十妖界起会掉落妖魄',
    enemyRespawn: '{0} 后刷新下一只妖物，备战可叠至 {1} 层',
    raidKeyDescription: '每日重置后可得讨伐令 {0} 枚，击败妖王可再得 {1} 枚',
    towerKeyDescription: '每开启一座塔消耗 {0} 枚镇妖塔钥，每周重置',
    taunt: '燃烧精血',
    taunt_title: '燃烧精血',
    taunt_description: '燃烧一缕精血，妖物一备好即强行出兵交战，纵使未备战亦可迎战（未备好则无掉落奖励）',
    taunt_on: '燃烧精血',
    taunt_off: '燃烧精血',
    taunt_clickToToggle: '点击切换',
    rename_hint: '点击修改道号',
    rename_prompt: '请输入新的道号：',
    equip: '装备',
    unequip: '卸下',
    maxed: '满级',
    upgrade: '道法升级',
    health: '生命',
    enemyDescription: '第 {0} 只妖物：攻 {4}、命 {5}、奖励 {6}',
    itemFindDescription: '在当前妖界发现此灵械的概率',
    raid_name: '讨伐',
    raid_title: '讨伐妖王',
    raid_description: '聚合讨伐令，围剿镇外的大妖王',
    raid_fight: '讨伐',
    raid_slay: '斩妖',
    raid_slayAll: '尽斩',
    raid_slayDescription: '消耗讨伐令，直接斩却当前妖王',
    raid_slayConvert: '斩杀奖励将转化为材料',
    raid_victory: '讨伐功勋',
    raid_victoryDescription: '你已累积 {0} 层讨伐功勋',
    raidboss: '讨伐妖王',
    raidbossDescription: '妖王实力随讨伐妖界 {0} 提升',
    raidbossFail: '此妖王已败',
    tower_description: '镇妖塔内层层妖怨盘踞，一探究竟'
  },

  /* ---------------- 货币 ---------------- */
  CURRENCY: {
    horde_bone: '妖骨',
    horde_monsterPart: '妖魄',
    horde_corruptedFlesh: '腐灵血肉',
    horde_mysticalShard: '玄晶碎',
    horde_soulCorrupted: '堕灵魄',
    horde_raidKey: '讨伐令',
    horde_towerKey: '镇妖塔钥',
    horde_crown: '妖王冕',
    horde_blood: '妖血',
    horde_lockpick: '灵枢撬',
    horde_monsterToothWarzone: '沙场妖牙',
    horde_monsterToothMonkeyJungle: '猴林妖牙',
    horde_monsterToothLoveIsland: '情岛妖牙'
  },

  /* ---------------- 属性（装备词条 / stat 显示） ---------------- */
  STAT: {
    health: '生命',
    energy: '元力',
    mana: '炁',
    attack: '攻击',
    defense: '守御',
    critChance: '会心率',
    critMult: '会心伤害',
    strength: '淬力',
    intelligence: '凝识',
    haste: '疾行',
    revive: '复生',
    divisionShield: '分阵护',
    respawn: '备战',
    firstStrike: '先手',
    toxic: '毒蚀',
    execute: '处决',
    spellblade: '灵剑诀',
    corruption: '磨蚀',
    bossRequirement: '妖王连斩需求',
    equipmentChance: '灵械寻获率',
    equipmentMasteryGain: '灵械道行',
    maxEquipment: '灵械栏位',
    physicTaken: '体元受创',
    skillPointsPerLevel: '升阶点',
    expBase: '历练积累',
    // 扩展：装备词条常见属性
    recovery: '回气',
    cutting: '破甲',
    shieldbreak: '碎盾',
    statusResist: '抗性',
    healing: '疗复',
    passiveRecovery: '息止回气',
    nostalgia: '溯念',
    heirloomChance: '传承寻获率',
    trinketGain: '灵饰寻获',
    shardChance: '灵钻寻获率',
    essenceGain: '精炁获取',
    autocast: '自动',
    manasteal: '夺炁',
    energyRegen: '元力回复',
    manaRegen: '炁回复',
    manaToHaste: '炁化疾行',
    energyToStr: '元力化劲',
    energyToEnergyReg: '元力化恢复',
    attackPerMissingHealth: '愈战愈勇',
    strIntPerMissingHealth: '困兽之斗',
    attackAfterTime: '久战攻伐',
    strIntAfterTime: '久战锻体',
    maxSacrifice: '献祭上限',
    sacrifice: '献祭',
    toothGain: '妖齿获取',
    courageScore: '勇气分值',
    prestigeIncome: '轮回收益',
    rareLootTime: '奇珍滞留时',
    maxTrinkets: '灵饰栏位'
  },

  /* ---------------- 灵械·装备 ---------------- */
  ITEM: {
    dagger: '冷月匕',
    shirt: '辟尘仙衣',
    guardianAngel: '金身不灭符',
    milkCup: '聚宝琉璃盏',
    starShield: '紫薇星盾',
    longsword: '青冥剑',
    spellbook: '河图洛书',
    shield: '玄武重盾',
    armor: '天罡玄武甲',
    blessedArmor: '八宝金锁甲',
    blessedBow: '穿云仙弓',
    blessedFlame: '圣火金乌焰',
    blessedShield: '降魔圣盾',
    blessedSword: '昊天镇魔剑',
    blessedWater: '净世玉净瓶',
    blessing: '天官赐福',
    bone: '妖骨',
    antidote: '辟邪解毒丹',
    basicSpear: '沥泉神枪',
    bigHammer: '巨灵神锤',
    bishop: '金刚佛', // 棋子·圣
    blazingStaff: '九龙神火杖',
    bomb: '九霄神雷弹',
    book: '无字天书',
    boots: '云履仙靴',
    bowTie: '彩蝶仙结',
    brokenStopwatch: '损天时仪',
    calmingPill: '静心安神丹',
    campfire: '不灭玄火',
    cat: '九命灵猫',
    chocolateMilk: '九转还魂饮',
    cleansingFluid: '涤魔仙泉',
    cleansingSpring: '清凉甘露泉',
    cloudStaff: '列缺神杖',
    clover: '四叶仙草',
    club: '如意金箍棒',
    corruptEye: '堕妖魔瞳',
    corruptedBone: '腐灵妖骨',
    critCore: '七窍玲珑心',
    cursedEye: '祸斗妖瞳',
    cutter: '破军刃',
    dangerShield: '凶煞镇盾',
    deadBird: '幽冥冥鸦',
    deathsword: '斩魂剑',
    doubleEdgedSword: '裂魂双刃剑',
    dragonheart: '吞天龙心',
    dumbbell: '玄铁镇仙锁',
    energyDrink: '山参养气露',
    essenceExtractor: '摄魂魔壶',
    evergrowingVine: '长生不灭藤',
    experimentalVaccine: '不死仙酿',
    fireOrb: '离火珠',
    firework: '金莲火树',
    forbiddenHeartShield: '噬心魔盾',
    forbiddenScissors: '金翅剪',
    forbiddenShield: '诛仙盾',
    forbiddenStopwatch: '浑天仪',
    forbiddenSword: '诛仙剑',
    forbiddenToxin: '灭仙毒露',
    glasses: '通天宝镜',
    glowingEye: '金睛火瞳',
    glue: '锁元凝胶',
    goldenStaff: '鎏金神杖',
    heavyGauntlet: '怒目金刚拳',
    hourglass: '遁光时砂',
    king: '天皇',
    knight: '天马',
    leechingStaff: '噬血魔杖',
    liver: '饕餮妖肝',
    luckyCharm: '五路财神符',
    mace: '降魔狼牙棒',
    mailbreaker: '破鳞锥',
    marblePillar: '擎天白玉柱',
    maskOfJoy: '大圣欢喜面',
    meatShield: '血煞肉盾',
    microscope: '显微天眼镜',
    mine: '九幽玄雷',
    moltenShield: '赤炎熔岩盾',
    mysticalAccelerator: '风火轮',
    natureStone: '补天青石',
    needle: '绣花神针',
    oppressor: '翻天印',
    pawn: '道兵',
    plaguebringer: '瘟神瘴幡',
    prism: '七宝琉璃棱镜',
    queen: '天后',
    rainbowStaff: '七宝虹杖',
    redStaff: '火尖枪',
    rook: '镇殿柱',
    scissors: '青竹仙剪',
    secretWeapon: '不周秘械',
    shatteredGem: '补天碎玉',
    shieldDissolver: '噬甲玄砂',
    snowflake: '六出冰花',
    spookyPumpkin: '幽冥鬼火瓜',
    stoneplate: '磐石土甲',
    strangeChemical: '诡变灵剂',
    toxicSword: '万蛊毒剑',
    toxin: '鸩羽毒灵',
    wizardHat: '太乙法冠'
  },

  /* ---------------- 战斗职业 ---------------- */
  CLASS: {
    adventurer: '云游散修',
    archer: '穿云弓修',
    assassin: '影杀客',
    cultist: '血祀巫',
    knight: '玄甲卫',
    mage: '玄门法修',
    pirate: '瀚海盗',
    scholar: '衍书儒',
    shaman: '巫祝',
    undead: '尸傀'
  },

  /* ---------------- 技能（基名，视图剥 _N 后缀后查表） ---------------- */
  SKILL: {
    health: '厚躯', health_2: '厚躯', health_3: '厚躯', health_4: '厚躯', health_5: '厚躯',
    strength: '淬力', strength_2: '淬力', strength_3: '淬力', strength_4: '淬力',
    intelligence: '凝识', intelligence_2: '凝识', intelligence_3: '凝识', intelligence_4: '凝识', intelligence_5: '凝识',
    energy: '蓄元', energy_2: '蓄元', energy_3: '蓄元', energy_4: '蓄元', energy_5: '蓄元',
    mana: '养炁', mana_2: '养炁', mana_3: '养炁', mana_4: '养炁',
    manaRest: '回炁',
    recover: '恬息', recovery: '复原',
    haste: '疾行', haste_2: '疾行', haste_3: '疾行', haste_4: '疾行',
    damage: '破招', damage_2: '破招', damage_3: '破招', damage_4: '破招',
    courage: '胆识',
    blood: '妖血',
    bloodOnCrit: '会心血涌',
    energyOnCrit: '会心元涌',
    critChance: '会心', critChance_2: '会心', critChance_3: '会心', critChance_4: '会心',
    critMult: '会心倍',
    critMult_2: '会心倍', critMult_3: '会心倍', critMult_4: '会心倍',
    healthOnCrit: '会心回生',
    healOnCrit: '会心愈伤',
    energyConvert: '元力化生',
    stab: '玄刺',
    combatHeal: '战愈',
    brawl: '乱斗',
    smallFireball: '小炎弹',
    smash: '撼地击',
    spark: '雷火迸',
    doubleStrike: '双重斩',
    fullRecovery: '满灵回元',
    supercharge: '聚元',
    lootSearch: '觅宝',
    sharpen: '砺锋',
    fireArrows: '焚灵箭',
    poisonArrow: '淬毒箭',
    shockArrow: '破煞箭',
    sharpMind: '明心',
    eagleEye: '鹰眼',
    forestBlessing: '灵林赐福',
    reduceCooldownOnCrit: '会心凝策',
    longshot: '远射',
    ashBlessing: '灵尘',
    backstab: '背刺',
    comboStrike: '连刺',
    firstStrike: '先手', firstStrike_2: '先手', firstStrike_3: '先手',
    elementOfSurprise: '奇袭',
    flow: '行云',
    knockout: '击晕',
    pickpocket: '顺手牵羊',
    shuriken: '手里剑',
    smokeBomb: '烟遁弹',
    sneak: '潜行',
    swiftStrike: '疾刺',
    cursedDagger: '咒刃',
    herbTea: '药茗',
    hiddenExplosive: '暗火',
    magicAttack: '法攻',
    meditation: '入定',
    spellblade: '灵剑诀',
    secretTechnique: '秘技',
    combustion: '燃魂',
    combatStance: '战立',
    corruption: '磨蚀',
    crimsonCurse: '赤咒',
    crimsonHeart: '赤心',
    crimsonPact: '赤契',
    crimsonRitual: '赤仪',
    darkRitual: '暗仪',
    despair: '绝望',
    drainLife: '蚀命',
    harvest: '收割',
    hex: '蛊咒',
    learningStance: '研习之姿',
    lootingStance: '掠夺之姿',
    occultRestoration: '秘复',
    occultThunder: '秘雷',
    reincarnation: '轮回',
    sacrificialDagger: '祭献灵匕',
    summonAbomination: '召孽',
    bioTaken: '命元受创',
    magicTaken: '炁元受创',
    physicTaken: '体元受创',
    blessing: '赐福',
    consecrate: '圣净',
    cutting: '锋锐',
    damageRamp: '渐增灾厄',
    statRamp: '渐增道行',
    defense: '守御', defense_2: '守御', defense_3: '守御',
    divisionShield: '分阵护', divisionShield_2: '分阵护',
    fortify: '固垒',
    heavyHit: '重击',
    parry: '格挡',
    refuge: '庇护',
    revive: '复生', revive_2: '复生',
    shieldBash: '盾击',
    smite2: '天诛',
    toxic: '毒蚀',
    ascend: '飞升',
    autocast: '自动', autocast_2: '自动', autocast_3: '自动',
    barrier: '玄罩',
    conjure: '召灵',
    deepFocus: '凝神',
    earthquake: '地动',
    fireball: '火球',
    focus: '聚灵',
    heal: '愈伤',
    iceBlast: '冰爆',
    magicMissile: '灵弹',
    manasteal: '汲炁',
    shockBlast: '雷震',
    smite: '天罚',
    spellblade_2: '灵剑诀',
    waterBolt: '水箭',
    bombToss: '掷弹',
    bottleOBrew: '药酿酒',
    bountyBoard: '悬赏榜',
    cannonball: '炮弹',
    challenge: '挑战', challenge_2: '挑战', challenge_3: '挑战', challenge_4: '挑战',
    invigoratingBottle: '振奋灵酒',
    lockpick: '撬锁', lockpick_2: '撬锁', lockpick_3: '撬锁',
    parrotAttack: '灵鹦袭',
    pirateShip: '妖帆船',
    plunder: '劫掠',
    treasureChest: '藏宝箱',
    trinket: '灵饰',
    bossBash: '碎王锤',
    quickDraw: '拔剑'
  },

  /* ---------------- 区域 ---------------- */
  AREA: {
    warzone: '断魂沙场',
    monkeyJungle: '灵猴古林',
    loveIsland: '情缘妖岛'
  },

  /* ---------------- 妖物 ---------------- */
  ENEMY: {
    puppy: '小狗妖',
    kitten: '小猫妖',
    bunny: '灵兔妖',
    deadBird: '死鸟妖',
    skeleton: '骷髅',
    piglet: '小猪妖',
    guineaPig: '豚灵',
    rabbit: '灵兔',
    seal: '海豹妖',
    koala: '考拉妖',
    panda: '熊猫妖',
    dartMonkey: '掷镖猴',
    monkeyWizard_1: '猴法妖',
    monkeyDefender: '护卫猴',
    monkeyMonk: '猴僧',
    monkeyWizard_2: '猴法妖',
    monkeyWizard_3: '猴法妖',
    strongMonkey: '壮猴妖',
    angryMonkey: '怒猴妖',
    officer_1: '妖哨',
    soldier_1: '妖卒',
    officer_2: '妖军官',
    soldier_2: '妖卒',
    officer_3: '妖统领',
    soldier_3: '妖卒',
    sniper: '妖狙手',
    hunter: '猎妖者'
  },

  /* ---------------- 妖王 ---------------- */
  BOSS: {
    chriz1: '赤煞·嘲风',
    chriz2: '赤煞·馁狠',
    mina: '魅影·玉罗',
    ohilio: '魔心·泱洪',
    ohilio_guard1: '魔心卫·左',
    ohilio_guard2: '魔心卫·右'
  },

  /* ---------------- 传承（传家宝） ---------------- */
  RELIC: {
    power: '神力',
    health: '厚躯',
    attackSpeed: '攻速',
    divisionShield: '分阵护',
    strength: '淬力',
    criticalChance: '会心',
    ...{},
    energyDrink: '灵茗'
  },

  /* ---------------- 灵饰 ---------------- */
  TRINKET: {
    automation: '自动',
    cure: '解救',
    duality: '阴阳',
    energize: '蓄神',
    energy: '蓄元',
    extraction: '汲取',
    fists: '拳蕴',
    haste: '疾行',
    learning: '研习',
    love: '情缘',
    magic: '玄法',
    precision: '精准',
    preservation: '保元',
    sparks: '灵火',
    stone: '磐石',
    strength: '淬力',
    toxins: '毒蚀',
    vitality: '生机',
    wisdom: '智慧',
    wrath: '怒火'
  },

  /* ---------------- 妖痕·印记 ---------------- */
  TAG: {
    physicTaken: '体元受创',
    magicTaken: '炁元受创',
    bioTaken: '命元受创',
    energyOnCrit: '会心元涌',
    energyToStr: '元力化力',
    energyToHaste: '元力化速'
  },

  /* ---------------- 法印 · 妖符 ---------------- */
  SIGIL: {
    angelic: '圣洁',
    bashing: '碎甲',
    berserk: '狂怒',
    burst: '爆裂',
    cold: '冰寒',
    cure: '解救',
    defense: '守御',
    drain: '汲命',
    executing: '处决',
    fireball: '火球',
    focus: '聚灵',
    foulBreath: '秽息',
    fury: '暴怒',
    generic: '泛用',
    growing: '生长',
    health: '厚躯',
    iceGiant: '冰巨人',
    incorporeal: '虚体',
    magic: '玄法',
    magicBolt: '灵弹',
    monstrousToughness: '凶蛮坚韧',
    nuke: '湮灭',
    power: '神力',
    precision: '精准',
    protection: '庇护',
    raidRage: '讨伐之怒',
    rainbow: '虹霓',
    recovery: '复原',
    resilience: '坚韧',
    resistance: '抗性',
    screaming: '尖啸',
    sharpened: '贯穿',
    shielding: '护盾',
    shocking: '雷击',
    sparks: '灵火',
    spitting: '吐息',
    strength: '淬力',
    toughness: '坚韧',
    toxic: '毒蚀',
    wisdom: '智慧'
  },

  /* ---------------- 妖煞·法印终结技 ---------------- */
  SIGILBOSS: {
    chriz_fireball: '焚天火球',
    chriz_heal: '赤煞愈灵',
    chriz_iceBlast: '冰狱爆',
    chriz_lightningStrike: '惊雷天罚',
    chriz_magicMissile: '魔核灵弹',
    cute_bark: '裂崖吠',
    cute_bite: '碎金咬',
    cute_claws: '撕天爪',
    cute_eatCarrot: '吞噬灵萝卜',
    cute_kick: '疾风踢',
    cute_ram: '破山撞',
    mina_charm: '摄魂媚音',
    monkey_dart: '掷镖',
    monkey_fire: '火染',
    monkey_ice: '冰封',
    monkey_lightning: '雷击',
    ohilio_megagun: '泱洪巨炮',
    pistol_gun: '铳',
    rifle_gun: '火铳',
    shotgun_gun: '散铳',
    sniper_gun: '狙铳',
    war_bandage: '战地裹伤',
    war_grenade: '战阵雷'
  },

  /* ---------------- 元素 ---------------- */
  ELEMENT: {
    ice: '冰煞',
    thunder: '雷煞',
    water: '水煞'
  },

  /* ---------------- 镇妖塔 ---------------- */
  TOWER: {
    brick: '青石塔',
    danger: '凶煞塔',
    fire: '焰狱塔',
    forest: '森古塔',
    ice: '玄冰塔',
    toxic: '毒瘴塔'
  },

  /* ---------------- 道法升级（常规） ---------------- */
  UPGRADE: {
    anger: '嗔怒焚天功',
    attack: '诛仙诀',
    boneBag: '乾坤骨袋',
    bones: '生财妖骨术',
    brownPaint: '褐泥镇煞诀',
    carving: '刻玺印符术',
    cleansingRitual: '诛邪荡魔阵',
    collector: '聚灵收宝术',
    combatLesson: '兵武启蒙篇',
    dodgingGuide: '云隐飞身诀',
    frostSpear: '凝霜寒枪诀',
    grindstone: '磨剑砺锋诀',
    grossBag: '秽土纳灵囊',
    health: '延命诀',
    hoarding: '聚宝囤奇术',
    lightningShield: '天雷护体诀',
    looting: '搜山敛财术',
    luckyArtifact: '五福转运器',
    luckyStrike: '转运神击',
    milestone: '破境升阶典',
    monsterBag: '须弥纳物袋',
    monsterSoup: '熬骨续命羹',
    mysticalBag: '玄黄储物囊',
    mysticalPower: '九转玄功',
    plunderSecret: '幽盗劫掠术',
    pocketKnife: '袖中匕首诀',
    prepareTheSacrifice: '血祀预备术',
    protectiveVest: '金丝护仙衣',
    purifier: '净邪除魔诀',
    redPaint: '朱砂诛邪诀',
    resilience: '金刚不坏功',
    rest: '龟息养生术',
    scalpel: '剖妖夺魂刀',
    stabbingGuide: '疾刺要诀',
    strangeDetector: '寻妖探宝术',
    strangePower: '混沌变异功',
    survivalGuide: '避祸延命诀',
    targetDummy: '傀儡练功偶',
    thickSkin: '九转玄龟功',
    training: '炼体淬金功',
    unlimitedAnger: '无量嗔怒功',
    waterBubble: '玄水护身术',
    weaponStorage: '万械藏兵库',
    whitePaint: '白灵画符诀'
  },

  /* ---------------- 道法升级（进阶·血骨） ---------------- */
  UPGRADE2: {
    banishingRitual: '驱邪荡魔阵',
    bloodRitual: '血祭焚天仪',
    bloodStorage: '血池秘库',
    darkAttack: '玄冥暗攻诀',
    darkDummy: '暗影练功偶',
    darkHealth: '玄冥暗躯功',
    darkMilestone: '玄冥阶碑典',
    darkShield: '玄冥暗护诀',
    endlessAnger: '永堕嗔怒功',
    fistFight: '罗汉拳罡',
    harvest: '万灵收割术',
    protectiveShell: '玄龟护壳术',
    secondChance: '凤凰涅槃术',
    syringe: '九转针命诀',
    toothNecklace: '妖牙灵串',
    toothSpear: '妖牙戮神枪',
    transfusion: '血噬移元术'
  },

  /* ---------------- 道法升级（玄阶） ---------------- */
  PREMIUM: {
    ancientExpertise: '古法精擅',
    ancientFortitude: '古躯坚韧',
    ancientFreezing: '古玄冰封',
    ancientHolding: '古渊镇封',
    ancientMystery: '古玄之谜',
    ancientPower: '古神道力',
    ancientReaping: '古裔收割',
    ancientRemembrance: '古忆',
    ancientSharpsight: '古明目',
    ancientSpirit: '古灵',
    ancientWealth: '古财',
    moreBlood: '更多妖血',
    moreBones: '更多妖骨',
    moreCourage: '更多胆识',
    moreMastery: '更多道行',
    moreMonsterParts: '更多妖魄',
    moreMonsterTeeth: '更多妖牙',
    morePower: '更增道力',
    moreSouls: '更多堕灵魄'
  },

  /* ---------------- 道法升级（轮回·转生） ---------------- */
  PRESTIGE: {
    advancedLuck: '高阶鸿运',
    ashCircle: '涅槃灰烬阵',
    balance: '天衡',
    beginnerLuck: '初阶鸿运',
    bloodChamber: '血狱密室',
    boneChamber: '骨狱密室',
    boneTrader: '幽冥骨贾',
    butcher: '血煞屠刀',
    candleCircle: '烛魂法阵',
    chaosCrate: '混沌妖箱',
    combatStudies: '战道研习',
    containmentChamber: '镇封之室',
    deepHatred: '夙怨焚心',
    defenseBook: '守御典册',
    defensiveStance: '守御之势',
    determination: '执念化刃',
    discovery: '探幽索隐',
    education: '传道授业',
    essenceCollector: '灵魄聚器',
    exoskeleton: '外骨甲',
    headhunter: '猎首夺魂',
    innerFocus: '内蕴',
    lastWill: '遗愿',
    limitBreak: '破限',
    mausoleum: '玄陵',
    milk: '灵泉',
    moreDummies: '更多靶偶',
    mysticalCondenser: '玄气凝器',
    offenseBook: '攻伐典册',
    pathfinder: '寻径',
    peace: '宁和',
    precision: '精准',
    purge: '涤荡',
    resolve: '决意',
    royalArmor: '皇御灵甲',
    royalBlessing: '皇赐灵福',
    royalButcher: '皇御屠刀',
    royalCrypt: '皇陵',
    royalSecret: '皇室秘藏',
    royalStorage: '皇库',
    royalSword: '皇御剑',
    secretStorage: '秘库',
    secretTraining: '秘修',
    soulCage: '魂笼',
    spiritLure: '灵诱',
    spoilsOfWar: '战利',
    stoneSkin: '石化金肤',
    templeExploration: '古庙探秘',
    university: '学府',
    victoryCelebration: '凯旋庆典',
    wrath: '怒火'
  },

  /* ---------------- 成就 ---------------- */
  ACHIEVEMENT: {
    blood: '妖血',
    bone: '妖骨',
    courage: '胆识',
    infiniteScore: '无尽之战',
    maxCorruptionKill: '至魔斩妖',
    maxDamage: '至强一击',
    maxMastery: '至大道行',
    maxZone: '至深妖界',
    maxZoneSpeedrun: '极限冲界',
    monsterPart: '妖魄',
    soulCorrupted: '堕灵魄',
    totalMastery: '累计道行',
    trinket: '灵饰',
    unlucky: '厄运缠身'
  }
};